# Generated by Django 6.0.1 on 2026-01-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='image',
            field=models.ImageField(blank=True, upload_to='app/media'),
        ),
    ]
