# Generated by Django 6.0.1 on 2026-01-24 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_sample_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=222)),
                ('desc', models.TextField()),
                ('product_image', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
    ]
